codecov:
  require_ci_to_pass: true
  notify:
    after_n_builds: 1
    wait_for_ci: true

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: yes
  require_head: yes
  hide_project_coverage: false

coverage:
  precision: 2
  round: down
  range: 30..100
  status:
    project:
      default:
        # Start slightly above current ~35.85% to ensure improvement pressure without impossible gate.
        target: 36%
        threshold: 1%
    patch:
      default:
        # Patch target a bit higher (encourage new code to be better than baseline). Increase gradually.
        target: 40%
        threshold: 2%

# Ramp Plan (not parsed by Codecov):
# - When project coverage >= 40%, set project target: 40%, patch: 45%
# - Then raise in ~5% increments keeping patch ~5% above project until reaching 70%,
#   after which you can adopt a 70/75 → 75/80 → 80/85 sequence.

ignore:
  - "docs/**"
  - "public/**"
  - "common/lib/**"
  - "**/node_modules/**"
