codecov:
  require_ci_to_pass: true
  notify:
    after_n_builds: 1
    wait_for_ci: true

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: yes
  require_head: yes
  hide_project_coverage: false

coverage:
  precision: 2
  round: down
  range: 70..100
  status:
    project:
      default:
        target: 85%
        threshold: 1%
    patch:
      default:
        target: 85%
        threshold: 1%

ignore:
  - "docs/**"
  - "public/**"
  - "common/lib/**"
  - "**/node_modules/**"
