# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install deps
        run: npm ci

      - name: Lint
        run: npm run lint --silent

      - name: Typecheck
        run: npm run typecheck --silent

      # Run tests with coverage (Vitest)
      - name: Test with coverage
        run: npm test -- --coverage

      # Upload coverage (tokenless public mode)
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage/lcov.info
          fail_ci_if_error: false
          verbose: true

      # Build production bundle
      - name: Build (Vite)
        run: npm run build --silent

      # Verify ORT sidecar distribution
      - name: Verify ORT distribution
        run: npm run build:verify --silent
