# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Lint
        run: npm run lint --silent

      - name: Typecheck
        run: npm run typecheck --silent

      # Run tests and produce coverage locally
      - name: Test with coverage
        run: npm test -- --coverage

      # Upload coverage to Codecov (after tests)
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage/lcov.info
          # Keep non-blocking: code review requested avoiding hard CI failures on transient upload issues.
          fail_ci_if_error: false
          verbose: true
          # Later you can gate failures only on main branch by templating this input.
          # Example:
          # fail_ci_if_error: ${{ github.ref == 'refs/heads/main' && 'true' || 'false' }}
          # Add flags/slug if you want more granular Codecov dashboards.

      # Ensure the production bundle still builds (catches missing imports/assets)
      - name: Build (Vite)
        run: npm run build

      # Optional: verify ORT sidecar/file integrity after build
      - name: Verify ORT distribution
        run: npm run build:verify
